export const FlagNotes = [
  {
    id: '1',
    label: 'No Flag',
    value: 'no_flag',
    color: 'black',
    size: 17,
    borderSize: 2,
  },

  {
    id: '3',
    label: 'Gray',
    value: 'gray',
    color: '#CFCFCF',
    size: 17,
    borderSize: 2,
  },
  {
    id: '4',
    label: 'Blue',
    value: 'blue',
    color: '#057FE1',
    size: 17,
    borderSize: 2,
  },
  {
    id: '5',
    label: 'Yellow',
    value: 'yellow',
    color: '#FFC107',
    size: 17,
    borderSize: 2,
  },
  {
    id: '6',
    label: 'Red',
    value: 'red',
    color: '#E91919',
    size: 17,
    borderSize: 2,
  },
  {
    id: '7',
    label: 'Green',
    value: 'green',
    color: '#009688',
    size: 17,
    borderSize: 2,
  },
  {
    id: '8',
    label: 'Purple',
    value: 'purple',
    color: '#9C27B0',
    size: 17,
    borderSize: 2,
  },
  {
    id: '9',
    label: 'Orange',
    value: 'orange',
    color: '#FF5722',
    size: 17,
    borderSize: 2,
  },
  {
    id: '10',
    label: 'Brown',
    value: 'brown',
    color: '#795548',
    size: 17,
    borderSize: 2,
  },
  {
    id: '11',
    label: 'Golden',
    value: 'golden',
    color: '#DB8301',
    size: 17,
    borderSize: 2,
  },
  {
    id: '12',
    label: 'Pink',
    value: 'pink',
    size: 17,
    color: '#E91E63',
    borderSize: 2,
  },
  {
    id: '2',
    label: 'New Entry',
    value: 'new_registration',
    color: '#00FFFF',
    size: 17,
    borderSize: 2,
  },
];

export const FlagSetType = [
  {
    id: '1',
    label: 'Immediately',
    value: 'immediately',
    size: 17,
    borderSize: 2,
  },
  {
    id: '2',
    label: 'Future Date',
    value: 'future_date',
    size: 17,
    borderSize: 2,
  },
];

export const FlagUnSetType = [
  {
    id: '1',
    label: 'No Unset Date',
    value: 'no_unset_date',
    size: 17,
    borderSize: 2,
  },
  {
    id: '2',
    label: 'Specify Unset Date',
    value: 'specify_unset_date',
    size: 17,
    borderSize: 2,
  },
];
