import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  pageHeadingRow: {
    width: '100%',
    paddingRight: 0,
    paddingLeft: 0,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  saferView: {
    height: '100%',
    // backgroundColor: '#fff',
  },
  button: {
    marginBottom: 10,
    marginRight: 8,
  },
  pageHeading: {
    width: '100%',
    height: '100%',
    padding: 20,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: '#B6488D',
    fontSize: 23,
  },
  eventCounting: {
    color: '#202B37',
  },
  eventRow: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    flexGrow: 1,
    padding: 25,
    paddingBottom: 0,
    borderRadius: 20,
    alignItems: 'center',
  },
  eventLeft: {
    width: '80%',
  },
  eventLeftHeading: {
    color: '#B6488D',
    fontSize: 18,
    marginBottom: 5,
    fontWeight: '600',
  },
  eventSubDetail: {
    color: '#262B35',
    fontSize: 15,
    lineHeight: 20,
  },
  iconStyle: {
    backgroundColor: '#0073DA',
    borderRadius: 50,
    height: 44,
    width: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: 16,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    padding: 10,
    borderRadius: 5,
  },
  buttonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  sectionHeading: {
    color: '#0073DA',
    paddingTop: 5,
    paddingBottom: 5,
    fontSize: 20,
  },
  attendenceButton: {
    marginLeft: 25,
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 5,
  },
  attendenceButtonContent: {
    backgroundColor: '#B6488D',
    borderRadius: 5,
    width: 'auto',
    color: '#fff',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  lessonNoteRow: {
    padding: 25,
    paddingTop: 0,
    paddingBottom: 0,
    marginTop: 15,
    borderTopColor: '#fff',
    borderTopWidth: 4,
    borderStyle: 'solid',
  },
  lessonContent: {
    width: '100%',
    borderBottomWidth: 1,
    marginTop: 10,
    paddingBottom: 20,
    borderColor: '#BFBFBF',
    borderStyle: 'dashed',
  },
  lessonText: {
    color: '#000',
    paddingLeft: 0,
    paddingTop: 5,
    paddingRight: 10,
    paddingBottom: 0,
    fontSize: 16,
  },
});
